
/*
Duy Anh Nguyen
May 1, 2020
UMSATS Avionics Tools
AvionicsTools.java
The Avionics Tools application.
*/

public class AvionicsTools extends javax.swing.JFrame
{
    // Private member
    private SerialCommunication serialComm = null;

    /* AvionicsTools()
    Constructor to create new form of 
    Avionics Tools Application.    
    */
    public AvionicsTools()
    {
        initComponents();
        
        // Setup serial communication line
        this.serialComm = new SerialCommunication(this); // Pass it this window to pull and send information to the form
        
        // Search for ports
        this.serialComm.searchPorts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        OptionTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        label_TopIcon = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        label_TopIcon1 = new javax.swing.JLabel();
        COM_Port_Select = new javax.swing.JComboBox<>();
        SerialConnect = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        label_TopIcon2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("UMSATS - Avionics Tools");
        setPreferredSize(new java.awt.Dimension(650, 360));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        OptionTab.setBorder(new javax.swing.border.MatteBorder(null));
        OptionTab.setToolTipText("");
        OptionTab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        label_TopIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/UMSATS_Rocket_Icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_TopIcon)
                .addContainerGap(584, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_TopIcon)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        label_TopIcon.getAccessibleContext().setAccessibleName("");
        label_TopIcon.getAccessibleContext().setAccessibleDescription("");

        OptionTab.addTab("Serial", jPanel2);

        label_TopIcon1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/UMSATS_Rocket_Icon.png"))); // NOI18N

        SerialConnect.setText("Connect");

        jLabel1.setText("Select COM Port");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_TopIcon1)
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(COM_Port_Select, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SerialConnect))
                    .addComponent(jLabel1))
                .addContainerGap(382, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(COM_Port_Select, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SerialConnect)))
                    .addComponent(label_TopIcon1))
                .addContainerGap(252, Short.MAX_VALUE))
        );

        OptionTab.addTab("Config", jPanel3);

        label_TopIcon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icon/UMSATS_Rocket_Icon.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(label_TopIcon2)
                .addContainerGap(584, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_TopIcon2)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        OptionTab.addTab("Plot", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OptionTab)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(OptionTab)
        );

        OptionTab.getAccessibleContext().setAccessibleName("serial");
        OptionTab.getAccessibleContext().setAccessibleDescription("Menu");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AvionicsTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AvionicsTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AvionicsTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AvionicsTools.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AvionicsTools().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> COM_Port_Select;
    private javax.swing.JTabbedPane OptionTab;
    private javax.swing.JToggleButton SerialConnect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel label_TopIcon;
    private javax.swing.JLabel label_TopIcon1;
    private javax.swing.JLabel label_TopIcon2;
    // End of variables declaration//GEN-END:variables

    
    public void add_COM_to_Select(final String COM_NAME)
    {
        this.COM_Port_Select.addItem(COM_NAME);
    }
    
}
